id: 35e50f8e-93d3-a97f-b045-37a39fee5ef2
type: entity
interactions: []
annotations:
  - namespace: c4modeler
    name: position
    value:
      5f4d0504-c56e-4e00-a400-df15ad03620e:
        x: -38.39664804469277
        y: 271.2346368715084
entityType: domain
fields:
  - name: name
    type: string
    description: Description for name
    isPublic: true
    enumerable: true
    annotations: []
  - name: description
    type: string
    description: Description for description
    isPublic: true
    enumerable: true
    annotations: []
  - name: suggestedPrice
    type: float
    description: Description for suggestedPrice
    isPublic: true
    enumerable: true
    annotations: []
  - name: availableItems
    type: integer
    description: Description for availableItems
    isPublic: true
    enumerable: true
    annotations: []
  - name: type
    type: ProductType
    description: Description for type
    isPublic: true
    enumerable: true
    annotations: []
name: Product
description: Description for NewEntity
associations:
  - target:
      entity: 7ae9ddb5-08fe-4f39-b71d-0ddfe8af75a7
      navigation: product
      foreignKey: productId
    type: associate
    multiplicity: one-to-many
